services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - ./backend:/app
    networks:
      - music-room-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: backend
    networks:
      - music-room-network

networks:
  music-room-network:
    driver: bridge